#!/bin/sh

echo "Compiling started!"
echo ""

filename="${1%.*}"

if [ -s $filename ]; then
  rm $filename
fi

if [ ${2} = "O0" ]; then
  echo "-O0 compiling"
  clang++-3.5 -std=c++11 -Wshadow -Wall -fsanitize=address,undefined -O0 -Dssu1 -D_GLIBCXX_DEBUG -o $filename $1
  #g++ -std=c++11 -Wshadow -Wall -Wextra -Wconversion -O0 -Dssu1 -D_GLIBCXX_DEBUG -o $filename $1
else
  if [ ${2} = "O2" ]; then
    echo "-O2 compiling"
    clang++-3.5 -std=c++11 -O2 -Dssu1 -o $filename $1
  else
    echo "Unknown option!"
  fi
fi

echo ""
if [ -s $filename ]; then
  echo "OK."
else
  echo "FAIL!"
fi

